services:
  backend:
    build:
      context: .
      args:
        PROJECT_ENV: "dev"
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/srv/backend/

  celery:
    build:
      context: .
      args:
        PROJECT_ENV: "dev"
    container_name: celery
    volumes:
      - .:/srv/backend/

  database:
    container_name: database

  redis:
    container_name: redis

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
