services:
  backend:
    env_file:
      - .env
    depends_on:
      - database
      - redis

  celery:
    command: celery -A backend worker -l info
    env_file:
      - .env
    depends_on:
      - database
      - redis

  database:
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-backend}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-backend}
      - POSTGRES_DB=${POSTGRES_DB:-backend}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7.4.0-alpine

volumes:
  postgres_data:
